receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'greeting-service'
          scrape_interval: 15s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: [ 'greeting:9000' ]
        - job_name: 'calculating-service'
          scrape_interval: 15s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: [ 'calculating:9000' ]

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: default
    username: admin
    password: demo123
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 10000

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp, clickhouse ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ loki, clickhouse ]
    metrics:
      receivers: [ prometheus ]
      processors: [ batch ]
      exporters: [ prometheus, clickhouse ]
