package com.example.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.dynamodb.model.enummurate.CustomerType;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@DynamoDBTable(tableName = "Customer")
@NoArgsConstructor
public class Customer {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String nickName;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "customerType")
    private CustomerType customerType;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createTime;
}