services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:2.52
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    environment:
      - RI_HOST=0.0.0.0
      - REDIS_URI=redis://redis:6379