MYSQL_USER: user
MYSQL_PASSWORD: password
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: testdb
SERVICE_CALCULATING_URL: http://localhost:8081
MANAGEMENT_SERVER_PORT: 9000
OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
