server:
  port: 8080
  version: "@project.version@" # gradle 의 프로젝트 버전을 주입받음
spring:
  application:
    name: service-greeting
  profiles:
    active:
      - common
      - dev
  config:
    import: "classpath:application-common.yml"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  observations:
    key-values:
      jdbc:
        query:
          enabled: true # JDBC 쿼리 실행을 관찰(Observation) 대상으로 등록
  metrics:
    distribution:
      percentiles-histogram:
        jdbc.query: true # SQL 실행 시간에 대한 히스토그램 생성 (슬로우 쿼리 감지용)

service:
  calculating:
    url: ${SERVICE_CALCULATING_URL}
