services:
  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - "./path/to/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./path/to/rules.yml:/etc/prometheus/rules.yml"
      - "./volume/prometheus:/prometheus"
    ports:
      - '9090:9090'
    command:
      - "--config.file=/etc/prometheus/prometheus.yml" # command 지정시 yml 위치 지정해줘야함.
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=2GB"
      - "--storage.tsdb.path=/prometheus"
  alertmanager:
    image: prom/alertmanager:v0.27.0
    volumes:
      - "./path/template:/etc/alertmanager/template"
      - "./path/to/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    ports:
      - '9093:9093'