services:
  mysql-shard-1:
    image: mysql:8.0.32
    container_name: ds0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_ds_0
    ports:
      - "3306:3306"
    volumes:
      - mysql-shard-1-data:/var/lib/mysql

  mysql-shard-2:
    image: mysql:8.0.32
    container_name: ds1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_ds_1
    ports:
      - "3307:3306"
    volumes:
      - mysql-shard-2-data:/var/lib/mysql

volumes:
  mysql-shard-1-data:
  mysql-shard-2-data:
